
# make fille created with kiss Keep It Simple Stupid
default:
	g++ -o GAG main.cpp OnUserCreate.cpp -lX11 -lGL -lpthread -lpng -lstdc++fs -std=c++17
run:
	g++ -o GAG main.cpp OnUserCreate.cpp -lX11 -lGL -lpthread -lpng -lstdc++fs -std=c++17
	./GAG
debug:
	g++ -o GAG main.cpp OnUserCreate.cpp -g -lX11 -lGL -lpthread -lpng -lstdc++fs -std=c++17